version: '3.8'
services:
  back:
    pull_policy: never
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: event_manager_back
    env_file:
      - .env
    ports:
      - '5000:5000'
  front:
    pull_policy: never
    depends_on:
      back:
        condition: service_started
    build:
      context: frontend
      dockerfile: Dockerfile
    image: event_manager_front
    env_file:
      - .env
    ports:
      - '3000:3000'