version: '3.8'
services:
  redis:
    pull_policy: never
    restart: always
    build:
      context: ./redis
      dockerfile: Dockerfile
      args:
        - REDIS_PASSWORD=${redis_password}
    image: event_manager_redis
    ports:
      - ${ext_redis_port}:6379
  back:
    pull_policy: never
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: event_manager_back
    depends_on:
      redis:
        condition: service_started
    env_file:
      - .env
    ports:
      - '5000:5000'
  front:
    pull_policy: never
    restart: always
    depends_on:
      back:
        condition: service_started
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACK_URL=${REACT_APP_BACK_URL}
    image: event_manager_front
    env_file:
      - .env
    ports:
      - '3000:3000'